void main() {
  //If-Else statement

  var salary = 10000;

  if (salary > 8000) {
    print("You get the pramotion");
  } else {
    print("You are not getting pramotion");
  }

  //If-Else and Else-If Leader statement

  var marks = 70;

  if (marks >= 90 && marks <= 100) {
    print("student $marks");
  } else if (marks >= 70 && marks <= 80) {
    print("B Grade");
  } else {
    print("you should go and study");
  }
}
