void main()
{
  String grade = 'A';
  
  //Switch Case statement, whhich is only applicable for only "int" and "string".
  switch(grade)
  {
    case 'A':
      print("Excellent work buddy");
      break;
    case 'B':
      print("You need to do little work");
      break;
    case 'C':
      print("You need to do work on your skils");
      break;
    default :
      print("Go to home and learn things");
      break;
  }
}